### ISSUE TITLE
Is there a way to wait to validate that the client can connect?

### ISSUE THREAD

**Issue by mcollina** [carlozamagni/fastify-google-cloud-storage#4]
The plugin should validate that it can communicate with the cloud before calling the callback.

**Comment by carlozamagni** [comment]
OK, i'll take care of it

**Comment by carlozamagni** [comment]
Just committed the aforementioned validation with related test. 
I'm not particularly fond of the solution but it works and is better than not knowing whether the configuration is correct or not.
